### ISSUE TITLE
lintr compatability

### ISSUE THREAD

**Issue by sje30** [krlmlr/styler#11]
This looks like a great project, and one that I'm watching with a view to ensuring it works well with Emacs and ESS.

Just wondering, are you aiming to be consistent with linters, e.g. https://github.com/jimhester/lintr

cc: @jimhester

**Comment by lorenzwalthert** [comment]
In the first place, we aim for consistency with the [tidyverse style guide](http://style.tidyverse.org). In a later stage, however, we plan to make styler configurable in the sense that a different set of rules can be applied to the code, not just the ones corresponding to the tidyverse style guide, as described in the [Google Summer of Code Proposal](https://github.com/rstats-gsoc/gsoc2017/wiki/Noninvasive-source-code-formatting/).

**Comment by sje30** [comment]
Thanks!  This sounds great.  I note the last line of the tidyverse guide says:

    To apply this style guide automatically, use lintr.

So I guess lintr and tidyverse and hence styler will all agree!

**Comment by jimhester** [comment]
One of the main reasons I wrote lintr was to enforce hadley's style guide (now the tidyverse style) on my own code (https://github.com/jimhester/lintr/issues/4).

I have actually wanted to write a better R formatter for 2.5 years now, but due to lack of time and deficiencies in the R parser (dropping comments) and data returned by `getParseData()` (no way to map from tokens into the AST) have not had time to do so.

It is actually somewhat unfortunate this package is not building on lintr directly, automatically fixing lints is a natural extension of generating them, and this package will have to duplicate much of the framework in parsing code and querying the AST and tokens.  I even have a simple post of [automatic conversion of the assignment operator](http://www.jimhester.com/blog/2016/07/25/assignment/) using lintr on my blog.

**Comment by sje30** [comment]
Thanks for the comments.  It sounds like there is much to share between the two approaches.

**Comment by krlmlr** [comment]
@jimhester: Thanks for your input. I think we have found a way to derive an AST-like data structure from the parse data, which will allow to fix indention and other formatting issues. I started a new package because

- I thought lintr's scope was just to detect lint, and not to fix it
- writing a reformatter from scratch looked easier than integrating it into the fairly large project that lintr already is.

If there's substantial overlap, we may well consider integrating it into lintr, but I'd prefer a working version in isolation first. At the very least we might want to reuse lintr's configuration file at a later stage of the project.

@lorenzwalthert: In any case I think it's worthwhile to look into the lintr code base if you have the time.
